### PR TITLE
Fix tasks parsing bug

### PR DESCRIPTION
**Pull request by tdb-alcorn**
## Summary

I ran into a bug when ending a set of options for a task with an empty line `""` instead of `"--"`. The parser failed to reset `task_skip_block = False` and consequently the rest of the config file was dropped for that task. This PR contains a test that was failing on the original branch, as well as a one line fix to correct this behavior at [sby.py:195](https://github.com/YosysHQ/SymbiYosys/compare/master...tdb-alcorn:fix-tasks-parser?expand=1#diff-697dcff044c4062a3740a16e97baeac0R195).

I've also moved all the non-function code in `sby.py` under the typical Python `if __name__ == '__main__':` guard, which enables importing the functions defined elsewhere for testing without kicking off an actual run.

## Details

In the example below there are two tasks, `a` and `b`, each with different options configured. Task `b` works but when running task `a` you will get `ERROR: Config file is lacking engine configuration`. It turns out that the entire config file after the `a` options is getting dropped due to a bug in the parser. This PR fixes it.

```
[tasks]
a
b

[options]
a:
mode prove
depth 100

b:
mode cover
depth 100

[engines]
smtbmc

[script]
read -formal foo.v
prep -top foo

[files]
foo.v
```

## Test

`cd` into the `sbysrc` folder and run

```
python3 -m unittest test_sby.py
```

The test should pass. If you revert one commit (`git checkout HEAD~1`) and run the above command again, the test should fail, exhibiting the bug.

### CODE REVIEW

**Comment by clairexen** [comment]
Quoting the documentation:
> If the tag \<taskname\>: is used on a line by itself then the conditional string extends until the next conditional block or -- on a line by itself.

Your code lacks that terminating `--` line at the end of the `b:` block.

**Comment by tdb-alcorn** [comment]
> until the next conditional block

I assume by "conditional block" you mean any options specified under a given task tag. Doesn't 

```
a:
mode prove
depth 100

b:
mode cover
depth 100
```

meet that description? The second conditional block started by `b:` should end the `a:` block. But currently Symbiyosys thinks the `a:` block continues indefinitely and so the rest of the config file is dropped.

Or is the documentation intended to mean that if there are any task tags in the options section, then the options section must be concluded with a `--` line? Apologies if I'm misunderstanding something.

**Comment by clairexen** [comment]
> But currently Symbiyosys thinks the a: block continues indefinitely

no, that's incorrect. The `b:` terminates the `a:` block, but the `b:` block continues indefinitely because there's no `--` line terminating it:

```
claire@hopper:~/Temp/stuff$ cat test.sby 
[tasks]
a
b

[options]
a:
mode prove
depth 100

b:
mode cover
depth 100

[engines]
smtbmc

[script]
read -formal foo.v
prep -top foo

[files]
foo.v
claire@hopper:~/Temp/stuff$ sby --dumpcfg test.sby a
[options]
mode prove
depth 100

claire@hopper:~/Temp/stuff$ sby --dumpcfg test.sby b
[options]
mode cover
depth 100

[engines]
smtbmc

[script]
read -formal foo.v
prep -top foo

[files]
foo.v
```

> Or is the documentation intended to mean that if there are any task tags in the options section, then the options section must be concluded with a -- line? Apologies if I'm misunderstanding something.

The pre-processor handling tasks doesn't know anything about sections. `<taskname>:` starts a block that;s conditional for only one task, and that block runs until there's another `<taskname>:` line, or a `--` line,

**Comment by tdb-alcorn** [comment]
Ok, I understand now. Thanks for taking the time to respond!

Would you be willing to entertain changing that behaviour to allow empty lines `""` to end a conditional block? IMO the expectation that an empty line would terminate a block in a configuration file is not totally misplaced, so other people might also try this and make this mistake. Also, the error that I got (`lacking engine configuration`) when that expectation was violated was difficult to connect to the actual problem.

**Comment by nakengelhardt** [comment]
Improving the error messages is an item on my to-do list. I'll keep this problem in mind and see what I can do on that end.

**Pull request closed without merging**
