### PR TITLE
Made into Python module

### PR DESCRIPTION
**Pull request by ChrisPattison**
Makes installation consistent with other Python projects
Example of installing into a new virtual environment and running demo3 with Z3 below
[sby_validation.txt](https://github.com/YosysHQ/SymbiYosys/files/2252258/sby_validation.txt)

### CODE REVIEW

**Comment by q3k** [comment]
Cool! I'll take a look at this later this week.

**Comment by 1138-4EB** [comment]
*ping* @q3k

**Comment by whitequark** [comment]
Looks reasonable to me, but should probably use relative imports (`from . import ...`) rather than absolute (`from sby import ...`).

**Comment by cjblocker** [comment]
It seems this doesn't install any executables, so you can only run it with `python -m sby`. Adding an entry_point into the setup.py could fix this.

I like that it separates the sby installation from the yosys installation, assuming that is not a problem. I have yosys installed in multiple places on my system, and it is unclear to me if running `sby` uses the first yosys in my path or the yosys' directory it installed itself in, by default.

**Comment by whitequark** [comment]
We discussed this on the last meeting. Although this isn't currently clearly stated anywhere (it probably should be), the reason SymbiYosys installation process looks the way it does is that SymbiYosys is a component of Yosys that depends on its internal unversioned APIs and is installed into the Yosys data directory.

In other words, currently, SymbiYosys should not be distributed and used as a separate component, but rather built and used as a part of a Yosys installation, even though it lives in a separate repository. Because of that I'm closing this PR.

**Comment by eine** [comment]
Hi @whitequark! I don't follow the reasoning... I understand that Yosys is a dependency of SymbiYosys, so the former needs to be installed for the latter to work. Moreover, since SymbiYosys depends on Yosys' internal unversioned API, there is no guarantee that any arbitrary commit of SymbiYosys will work with any arbitrary commit of Yosys. Compatibility is not documented. I'm ok with all of that, since that's the same context with ghdl, yosys and ghdl-yosys-plugin.

However, I don't understand the requirement to install SymbiYosys in Yosys' data directory. That sounds as a convention and not a technical requirement/limitation. To be precise, in ghdl/docker, SymbiYosys is installed separatedly in a different directory and AFAIA it works as expected. In fact, `ghdl.so` can also be optionally installed in Yosys, but it is not a requirement.

> SymbiYosys should not be distributed and used as a separate component, but rather built and used as a part of a Yosys installation

In order to enforce that, I think it would be desirable for SymbiYosys to be a submodule of Yosys, and to be installed as an option/argument of a regular Yosys build. However, the disadvantage of that approach is that users are forced to run the regular installation procedure, even if they want to install SymbiYosys only (e.g., because they already have a pre-built Yosys).

Hence, I'd like you to reconsider closing this issue. Acknowledging that this repo is optional and can be handled as a regular Python module allows useful development setups; such as using `PYTHONPATH` to test a development version of SymbiYosys, without modifying the system installataion.

**Comment by whitequark** [comment]
> However, I don't understand the requirement to install SymbiYosys in Yosys' data directory.

> However, the disadvantage of that approach is that users are forced to run the regular installation procedure, even if they want to install SymbiYosys only (e.g., because they already have a pre-built Yosys).

For context, I was originally in favor of this change, which I wanted to use to ship sby as a separate, independent tool in [YoWASP](https://yowasp.org). I wasn't aware of the rationale for having `make install` here, which is that sby is a Yosys component (that happens to be located in a different repository), and which you might want to have installed *per Yosys build tree*. If you install it globally, there's no guarantee that it will match your Yosys tree, or keep matching it once you upgrade Yosys.

After learning this rationale, I reconsidered and will ship SymbiYosys as a part of the main YoWASP Yosys package.

> even if they want to install SymbiYosys only (e.g., because they already have a pre-built Yosys).

Then perhaps that is the problem here? That is, Yosys packagers should build and ship SymbiYosys as a part of the corresponding Yosys package, but currently don't.

> Hence, I'd like you to reconsider closing this issue.

That isn't my personal decision; I was acting according to the consensus reached on a meeting of Yosys maintainers. You may ask @clairexen to reconsider, though.

**Comment by eine** [comment]
> Then perhaps that is the problem here? That is, Yosys packagers should build and ship SymbiYosys as a part of the corresponding Yosys package, but currently don't.

I had not understood that SymbiYosys should be included with Yosys (not optional) from now on. If that is the case, all good!

**Comment by whitequark** [comment]
> I had not understood that SymbiYosys should be included with Yosys (not optional) from now on.

Sorry, I was unclear. SymbiYosys is not a mandatory component of Yosys, just like Tcl or pyosys or abc or readline or a number of other components are not mandatory per se. But if a package aims to be *complete*--for example Debian packages usually build with as many features as possible--then this package should surely include SymbiYosys.

**Comment by ChrisPattison** [comment]
As a historical perspective: Let me say that at the time I opened this PR (almost 2 years ago), it wasn't obvious that SymbiYosys was coupled so tightly to Yosys. It also wasn't (isn't?) so obvious either how one should use `sby` without modifying the system python installation which is generally a good way to break things.

**Comment by whitequark** [comment]
> it wasn't obvious that SymbiYosys was coupled so tightly to Yosys

It wasn't obvious to me today either, and frankly still isn't. This should probably be explained better.



> It also wasn't (isn't?) so obvious either how one should use `sby` without modifying the system python installation which is generally a good way to break things.

`make install` doesn't modify the system Python installation, does it? It installs to the Yosys data directory:

https://github.com/YosysHQ/SymbiYosys/blob/cddfebe029e9f4d76ccdbd3152b9523c641cfaf0/Makefile#L26-L27

**Pull request closed without merging**
